### ISSUE TITLE
serve used in jest jest-puppeteer.config.js, but not in dependencies

### ISSUE THREAD

**Issue by Reinoptland** [dev-mastery/my-fave-posters#1]
Hi there!

I was trying out this tutorial and jest setup and I noticed the following error while running `npm run test:ui`:

![Screen Shot 2019-06-19 at 21 07 33](https://user-images.githubusercontent.com/20372832/59794356-1175c480-92d9-11e9-917e-ffe32050a822.png)

Seems like serve is installed globally, but it might be smoother not assume that it is.

I will submit PR's to the branches of your repo to fix the issue.

Many thanks for making this insightful tutorial!

**Comment by arcdev1** [comment]
Good catch. I would certainly welcome a PR:

**Comment by Reinoptland** [comment]
👍 

#2 
#3 
#4

**Comment by arcdev1** [comment]
fixed by #4

**Comment by arcdev1** [comment]
fixed by #2, #3, and #4
